function demo_face_screen_arm_joint_sliders(workspaceMode)
%DEMO_FACE_SCREEN_ARM_JOINT_SLIDERS Interactive joint slider controller.
%
% Usage:
%   demo_face_screen_arm_joint_sliders
%   demo_face_screen_arm_joint_sliders("wide")
%
% Slider units:
%   J1/J2/J3/J5/J6: degrees
%   J4: millimeters
%
% This is a kinematics visualization demo. It updates the rigidBodyTree joint
% configuration directly and does not simulate motors, forces, or collisions.

if nargin < 1 || strlength(string(workspaceMode)) == 0
    workspaceMode = "large";
else
    workspaceMode = lower(string(workspaceMode));
end

projectRoot = fileparts(fileparts(mfilename("fullpath")));
urdfPath = fullfile(projectRoot, "generated", "urdf", "face_screen_support_arm.urdf");

robot = importrobot(urdfPath);
robot.DataFormat = "column";
robot.Gravity = [0 0 -9.81];

jointDefs = createJointDefinitions();
q = displayValuesToConfig([0, -120, 120, 30, 0, 0]);

fig = figure( ...
    "Name", "Face Screen Support Arm Joint Control", ...
    "NumberTitle", "off", ...
    "Color", "w", ...
    "MenuBar", "none", ...
    "ToolBar", "figure", ...
    "Visible", "on", ...
    "Units", "normalized", ...
    "Position", [0.08, 0.10, 0.82, 0.78]);

ax = axes( ...
    "Parent", fig, ...
    "Units", "normalized", ...
    "Position", [0.05, 0.08, 0.62, 0.86]);

controlsPanel = uipanel( ...
    "Parent", fig, ...
    "Title", "Joint Control", ...
    "Units", "normalized", ...
    "Position", [0.70, 0.08, 0.27, 0.86], ...
    "BackgroundColor", "w");

state = struct;
state.robot = robot;
state.q = q;
state.ax = ax;
state.workspaceMode = workspaceMode;
state.jointDefs = jointDefs;
state.sliders = gobjects(6, 1);
state.valueTexts = gobjects(6, 1);
state.listeners = cell(6, 1);
state.isUpdatingUi = false;

guidata(fig, state);
createControls(fig, controlsPanel);
redrawRobot(fig);

assignin("base", "robot", robot);
assignin("base", "q", q);
assignin("base", "jointControlFigure", fig);

fprintf("Joint slider demo started. Variables: robot, q, jointControlFigure\n");
end

function jointDefs = createJointDefinitions()
jointDefs = struct( ...
    "name", { ...
        "joint1_base_yaw", ...
        "joint2_shoulder_pitch", ...
        "joint3_elbow_pitch", ...
        "joint4_telescopic", ...
        "joint5_screen_pan", ...
        "joint6_screen_pitch"}, ...
    "label", { ...
        "J1 Base yaw", ...
        "J2 Shoulder pitch", ...
        "J3 Elbow pitch", ...
        "J4 Telescopic", ...
        "J5 Screen pan", ...
        "J6 Screen pitch"}, ...
    "unit", {"deg", "deg", "deg", "mm", "deg", "deg"}, ...
    "min", {-150, -180, -120, 0, -180, -60}, ...
    "max", {150, 0, 150, 280, 180, 60});
end

function createControls(fig, panel)
state = guidata(fig);

uicontrol( ...
    "Parent", panel, ...
    "Style", "text", ...
    "String", "拖动滑块直接控制每个关节", ...
    "Units", "normalized", ...
    "Position", [0.06, 0.94, 0.88, 0.035], ...
    "HorizontalAlignment", "left", ...
    "BackgroundColor", "w");

top = 0.86;
rowHeight = 0.115;

for i = 1:6
    y = top - (i - 1) * rowHeight;
    joint = state.jointDefs(i);

    uicontrol( ...
        "Parent", panel, ...
        "Style", "text", ...
        "String", sprintf("%s (%s)", joint.label, joint.unit), ...
        "Units", "normalized", ...
        "Position", [0.06, y + 0.040, 0.60, 0.035], ...
        "HorizontalAlignment", "left", ...
        "BackgroundColor", "w");

    state.valueTexts(i) = uicontrol( ...
        "Parent", panel, ...
        "Style", "text", ...
        "String", formatDisplayValue(configToDisplayValue(state.q(i), joint), joint.unit), ...
        "Units", "normalized", ...
        "Position", [0.66, y + 0.040, 0.28, 0.035], ...
        "HorizontalAlignment", "right", ...
        "BackgroundColor", "w");

    state.sliders(i) = uicontrol( ...
        "Parent", panel, ...
        "Style", "slider", ...
        "Min", joint.min, ...
        "Max", joint.max, ...
        "Value", configToDisplayValue(state.q(i), joint), ...
        "SliderStep", sliderStep(joint), ...
        "Units", "normalized", ...
        "Position", [0.06, y, 0.88, 0.040], ...
        "Callback", @(src, ~) sliderChanged(fig, src));

    state.listeners{i} = addlistener( ...
        state.sliders(i), ...
        "Value", ...
        "PostSet", ...
        @(~, event) sliderChanged(fig, event.AffectedObject));
end

buttonY = 0.075;
buttonH = 0.045;
buttonW = 0.265;
buttonGap = 0.028;

uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Home", ...
    "Units", "normalized", ...
    "Position", [0.06, buttonY + 2 * (buttonH + buttonGap), buttonW, buttonH], ...
    "Callback", @(~, ~) applyNamedPose(fig, "home"));
uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Near", ...
    "Units", "normalized", ...
    "Position", [0.37, buttonY + 2 * (buttonH + buttonGap), buttonW, buttonH], ...
    "Callback", @(~, ~) applyNamedPose(fig, "near"));
uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Far", ...
    "Units", "normalized", ...
    "Position", [0.68, buttonY + 2 * (buttonH + buttonGap), buttonW, buttonH], ...
    "Callback", @(~, ~) applyNamedPose(fig, "far"));
uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Left", ...
    "Units", "normalized", ...
    "Position", [0.06, buttonY + buttonH + buttonGap, buttonW, buttonH], ...
    "Callback", @(~, ~) applyNamedPose(fig, "left"));
uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Right", ...
    "Units", "normalized", ...
    "Position", [0.37, buttonY + buttonH + buttonGap, buttonW, buttonH], ...
    "Callback", @(~, ~) applyNamedPose(fig, "right"));
uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Zero", ...
    "Units", "normalized", ...
    "Position", [0.68, buttonY + buttonH + buttonGap, buttonW, buttonH], ...
    "Callback", @(~, ~) applyDisplayValues(fig, [0, 0, 0, 0, 0, 0]));

uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Export q", ...
    "Units", "normalized", ...
    "Position", [0.06, buttonY, 0.42, buttonH], ...
    "Callback", @(~, ~) exportCurrentConfig(fig));
uicontrol( ...
    "Parent", panel, ...
    "Style", "pushbutton", ...
    "String", "Close", ...
    "Units", "normalized", ...
    "Position", [0.52, buttonY, 0.42, buttonH], ...
    "Callback", @(~, ~) close(fig));

guidata(fig, state);
end

function step = sliderStep(joint)
range = joint.max - joint.min;
smallStep = 1 / range;
bigStep = 10 / range;
step = [smallStep, bigStep];
end

function sliderChanged(fig, slider)
if ~isvalid(fig)
    return
end

state = guidata(fig);
if state.isUpdatingUi
    return
end

index = find(state.sliders == slider, 1);
if isempty(index)
    return
end

joint = state.jointDefs(index);
displayValue = slider.Value;
state.q(index) = displayValueToConfig(displayValue, joint);
state.valueTexts(index).String = formatDisplayValue(displayValue, joint.unit);
guidata(fig, state);

redrawRobot(fig);
assignin("base", "q", state.q);
end

function applyNamedPose(fig, poseName)
poses = containers.Map;
poses("home") = [0, -120, 120, 30, 0, 0];
poses("left") = [45, -35, -45, 120, -90, 10];
poses("right") = [-45, -35, -45, 120, 90, 10];
poses("near") = [0, -55, -55, 20, 0, 5];
poses("far") = [0, -20, -20, 280, 0, 0];

applyDisplayValues(fig, poses(poseName));
end

function applyDisplayValues(fig, displayValues)
state = guidata(fig);
state.isUpdatingUi = true;

for i = 1:6
    joint = state.jointDefs(i);
    value = min(max(displayValues(i), joint.min), joint.max);
    state.sliders(i).Value = value;
    state.valueTexts(i).String = formatDisplayValue(value, joint.unit);
    state.q(i) = displayValueToConfig(value, joint);
end

state.isUpdatingUi = false;
guidata(fig, state);
redrawRobot(fig);
assignin("base", "q", state.q);
end

function exportCurrentConfig(fig)
state = guidata(fig);
assignin("base", "q", state.q);

displayValues = zeros(1, 6);
for i = 1:6
    displayValues(i) = configToDisplayValue(state.q(i), state.jointDefs(i));
end
assignin("base", "jointDisplayValues", displayValues);

fprintf("Exported q and jointDisplayValues to base workspace.\n");
fprintf("jointDisplayValues = [%.1f %.1f %.1f %.1f %.1f %.1f]\n", displayValues);
end

function redrawRobot(fig)
state = guidata(fig);

show(state.robot, state.q, ...
    "Visuals", "on", ...
    "Collisions", "off", ...
    "Frames", "off", ...
    "Parent", state.ax, ...
    "PreservePlot", false, ...
    "FastUpdate", true);

setupAxes(state.ax, state.workspaceMode);
title(state.ax, "Interactive joint control")
drawnow limitrate
end

function q = displayValuesToConfig(displayValues)
q = zeros(6, 1);
defs = createJointDefinitions();
for i = 1:6
    q(i) = displayValueToConfig(displayValues(i), defs(i));
end
end

function value = displayValueToConfig(displayValue, joint)
if joint.unit == "deg"
    value = deg2rad(displayValue);
else
    value = displayValue / 1000;
end
end

function displayValue = configToDisplayValue(configValue, joint)
if joint.unit == "deg"
    displayValue = rad2deg(configValue);
else
    displayValue = configValue * 1000;
end
end

function text = formatDisplayValue(value, unit)
if unit == "deg"
    text = sprintf("%7.1f deg", value);
else
    text = sprintf("%7.1f mm", value);
end
end

function setupAxes(ax, workspaceMode)
axis(ax, "equal")
grid(ax, "on")
view(ax, 135, 25)

switch workspaceMode
    case "normal"
        limits = [-0.75, 0.75; -0.75, 0.75; -0.10, 0.75];
    case "large"
        limits = [-1.50, 1.50; -1.50, 1.50; -0.10, 1.25];
    case "wide"
        limits = [-2.50, 2.50; -2.50, 2.50; -0.10, 1.75];
    otherwise
        error("Unknown workspace mode '%s'. Use normal, large, or wide.", workspaceMode);
end

xlim(ax, limits(1, :))
ylim(ax, limits(2, :))
zlim(ax, limits(3, :))
xlabel(ax, "X / m")
ylabel(ax, "Y / m")
zlabel(ax, "Z / m")
end
